### ISSUE TITLE
i can't use v1.1.1, need help

### ISSUE THREAD

**Issue by jalin107** [tredoe/osutil#10]
`go: github.com/tredoe/osutil@v1.1.1: verifying go.mod: checksum mismatch
        downloaded: h1:wHEjPMepmXQXkZhf9H4sQcCtmC45KuFo5VR97zG9/dY=
        sum.golang.org: h1:fx79htI3WZA9Ep4jphLFq06l3iRDimfOWTrkKOz+OAA=

SECURITY ERROR
This download does NOT match the one reported by the checksum server.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.`

**Comment by tredoe** [comment]
Try other version

**Comment by tredoe** [comment]
I've done some changes that have broken the API because I removed the repository fileutil to add it here. I'd seen if my packages were beung used by some project of open source and since they weren't I decided to remove fileutil.

Sorry for the inconvenience! The only soliution is try to use the last version and fix the API in your application.

**Comment by tredoe** [comment]
I'm trying fix it. I've recovered fileutil from a backup and I'm going to create v2 with new changes for osutil.

**Comment by tredoe** [comment]
Is it working now?

**Comment by tredoe** [comment]
Use v1.0.6 or v2.0.0 (although it is not stable)

**Comment by tredoe** [comment]
Somebody confirmes that v1.0.6 works without any breaking changes.
