### ISSUE TITLE
github.com/tredoe/osutil@v1.3.5 requires github.com/tredoe/goutil@v1.0.2

### ISSUE THREAD

**Issue by chubin** [tredoe/osutil#14]
I am sorry for creating a new issue for the same problem, but after the recent changes (today? yesterday?) it is not even possible to compile any project that uses `tredoe/osutil` so all CI jobs are red now.

The problem:

```
go: github.com/tredoe/osutil@v1.3.5 requires
	github.com/tredoe/goutil@v1.0.2: reading github.com/tredoe/goutil/go.mod at revision v1.0.2: unknown revision v1.0.2
```

I wonder where the 1.3.5 version comes from; `go.sum` references v1.0.6.

Anyway, this is broken now.

**Comment by tredoe** [comment]
Use the version v1.0.6

**Comment by chubin** [comment]
I use it. I mean I try to use it, but that's the error that I get in this case. I can post you the whole data

**Comment by chubin** [comment]
```
$ grep osutil src/go.*
src/go.mod:	github.com/tredoe/osutil v1.0.6
src/go.sum:github.com/tredoe/osutil v1.0.6 h1:KJvG9AFmUPLe3hsNKyPMIjNx77CkAJtMKVS4ugAT7vM=
src/go.sum:github.com/tredoe/osutil v1.0.6/go.mod h1:zNq93p2DLHJWkHi2/+zi3xOjZl8xxiv3tiI2A6zcB3w=
```
Ok, now let's try to build it:

```
$ make
xxx/xxx.go:32:2: no required module provides package github.com/tredoe/osutil/userutil/crypt/sha512_crypt; to add it:
	go get github.com/tredoe/osutil/userutil/crypt/sha512_crypt
```

Now let's try to get it:

```
$ go get github.com/tredoe/osutil/userutil/crypt/sha512_crypt
go get: github.com/tredoe/osutil@v1.0.6 updating to
	github.com/tredoe/osutil@v1.3.5 requires
	github.com/tredoe/goutil@v1.0.2: reading github.com/tredoe/goutil/go.mod at revision v1.0.2: unknown revision v1.0.2
```

I don't even mention 1.3.5 in my code:

```
$ grep -r '1\.3\.5' .
./src/go.sum:github.com/golang/protobuf v1.3.5/go.mod h1:6O5/vntMXwX2lRkT1hjjk0nAC1IDOTvTlVgjlRvqsdk=
./src/go.sum:github.com/yuin/goldmark v1.3.5/go.mod h1:mwnBkeHKe2W/ZEtQ+71ViKU8L12m81fl3OWwC1Zlc8k=
$
```

**Comment by tredoe** [comment]
Try to clean the modules cache using `go clean --modcache`

**Comment by chubin** [comment]
No. it does not help.

```
$ sudo rm -rf ~/go/ ~/.cache/go-build/
$ make
....
go: downloading github.com/Azure/go-autorest/autorest/to v0.4.0
xxx/xxx.go:32:2: no required module provides package github.com/tredoe/osutil/userutil/crypt/sha512_crypt; to add it:
	go get github.com/tredoe/osutil/userutil/crypt/sha512_crypt
Makefile:29: recipe for target 'build' failed
make: *** [build] Error 1

$ go get github.com/tredoe/osutil/userutil/crypt/sha512_crypt
go: downloading github.com/tredoe/osutil v1.3.5
go get: github.com/tredoe/osutil@v1.0.6 updating to
	github.com/tredoe/osutil@v1.3.5 requires
	github.com/tredoe/goutil@v1.0.2: reading github.com/tredoe/goutil/go.mod at revision v1.0.2: unknown revision v1.0.2
```

**Comment by tredoe** [comment]
You are using a make file. Do tou have tried to compile it using `go build`?

**Comment by chubin** [comment]
Sure; that's `go build` what is called in `Makefile`:

```
go build -ldflags="-s -w -X main.version=0.3.3.56" -o ../prg  .src/
```

I think you can easily reproduce it, if you just create a small program
which imports `crypt/sha512_crypt/` and try to build it in a clean environment.

**Comment by colin-sitehost** [comment]
I think this stems from the fact that `v1.0.6` < `v1.3.5`, and the go toolchain automatically picks the latest. Since you chose to revert the breaking change, you still need to invalidate those old versions (see below), and deleting them from the repo is not sufficient as the live forever in proxy.golang.org. 

The simplest option is to cotagging `v1.0.6` as `v1.4.0`, which will serve to make `go get github.com/tredoe/osutil` point at the commit currently tagged as `v1.0.6`. Then you can continue to do bugfixes from there. This does leave those old versions dangling, but you may not care.
```sh
git tag v1.0.6 v1.4.0
git push --tags
```

Another option is to release `v1.3.6`, a with `retract` statements such that all the tags you deleted  (including `v1.3.6`) are burned. This is my preferred resolution, so that all consumers of those versions will be notified and revert or upgrade.
```go.mod
retract (
        v1.1.1 // breaking change
        v1.1.2 // breaking change
        v1.1.3 // breaking change
        v1.1.4 // breaking change
        v1.1.5 // breaking change
        v1.1.6 // breaking change
        v1.1.7 // breaking change
        v1.1.8 // breaking change
        v1.2.0 // breaking change
        v1.2.1 // breaking change
        v1.3.0 // breaking change
        v1.3.1 // breaking change
        v1.3.2 // breaking change
        v1.3.3 // breaking change
        v1.3.4 // breaking change
        v1.3.5 // breaking change
        v1.3.6 // retract breaking releases
)
```

--- 

While I have your ear, I will also note that deleting tags is BAD and should not be done. This [violates semver](https://semver.org/#what-do-i-do-if-i-accidentally-release-a-backwards-incompatible-change-as-a-minor-version), and makes the module toolchain behave poorly. Note that all of the following tags still exist for go-get:
```
[user@localhost ~]$ curl proxy.golang.org/github.com/tredoe/osutil/@v/list
v1.3.0
v2.0.0-rc.6+incompatible
v1.0.2
v2.0.0-rc.3+incompatible
v1.0.5
v1.0.0
v1.0.6
v1.3.3
v1.1.6
v1.1.1
v1.3.1
v1.3.4
v1.0.3
v1.1.3
v2.0.0-rc.8+incompatible
v1.1.2
v2.0.0-rc.2+incompatible
v1.3.2
v1.2.1
v1.0.4
v2.0.0-rc.7+incompatible
v1.1.5
v1.1.4
v1.2.0
v2.0.0-rc.9+incompatible
v2.0.0-rc.4+incompatible
v1.1.8
v2.0.0-rc.1+incompatible
v1.3.5
v2.0.0-rc+incompatible
v1.0.1
v1.1.7
```
```
[user@localhost ~]$ curl proxy.golang.org/github.com/tredoe/osutil/v2/@v/list
v2.0.0-rc.7
v2.0.0-rc.8
v2.0.0-rc.3
v2.0.0-rc.16
v2.0.0-rc
v2.0.0-rc.1
v2.0.0-rc.4
v2.0.0-rc.9
v2.0.0
v2.0.0-rc.6
v2.0.0-rc.10
v2.0.0-rc.12
v2.0.0-rc.2
v2.0.0-rc.14
v2.0.0-rc.15
v2.0.0-rc.11
```

**Comment by tredoe** [comment]
@colin-sitehost, thank you very much!

But the issue is that I've done a lot of changes at master. So I'm supposed that the best solution is to remove all changes until the last main version v1. Then, to release v1.3.6, with the retract statement (as you said)

And finally, to add all files into the last commit for v2. Is it right?

**Comment by colin-sitehost** [comment]
It is not required that tags track master, I would suggest you make a v1 branch based off `v1.0.6`, and do everything there. Let me know if more details would be useful.

**Comment by tredoe** [comment]
Done! I hope it works!

**Comment by colin-sitehost** [comment]
I can confirm:
```
[user@localhost ~]$ go get github.com/tredoe/osutil
go get: added github.com/tredoe/osutil v1.0.6
```

**Comment by tredoe** [comment]
@colin-sitehost I already had retracted v2.0.0 in branch v2:

https://github.com/tredoe/osutil/blob/v2/v2/go.mod

**Comment by colin-sitehost** [comment]
go-get is not seeing that:
```
[user@localhost ~]$ go get github.com/tredoe/osutil/v2
go: downloading github.com/tredoe/osutil/v2 v2.0.0
```
it seems that `v2.0.1` was never discovered:
```
[user@localhost ~]$ curl proxy.golang.org/github.com/tredoe/osutil/v2/@v/list
v2.0.0-rc.7
v2.0.0-rc.8
v2.0.0-rc.3
v2.0.0-rc.16
v2.0.0-rc
v2.0.0-rc.1
v2.0.0-rc.4
v2.0.0-rc.9
v2.0.0
v2.0.0-rc.6
v2.0.0-rc.10
v2.0.0-rc.12
v2.0.0-rc.2
v2.0.0-rc.14
v2.0.0-rc.15
v2.0.0-rc.11
```

**Comment by tredoe** [comment]
I added it for when I add the next stable version (v2.0.1).
By now, there are many changes in the API

**Comment by colin-sitehost** [comment]
so, to confirm: do you intend to use `v2.0.1` as a stable release or exclusively to unrelase `v2.0.0`?

currently your [v2/go.mod](https://github.com/tredoe/osutil/blob/v2/v2/go.mod) is setup to do the latter, and you should publish it immediately, since it will self retract, and none of the pending changes will be consumable.

If you would rather just wait, your go.mod should look like so:
```go.mod
module github.com/tredoe/osutil/v2

go 1.16

require (
	github.com/smartystreets/goconvey v1.6.4 // indirect
	gopkg.in/ini.v1 v1.62.0
)

retract (
	v2.0.0 // breaking changes
)
```

It is also unnecessary to retract pre-release versions, as they will never show up as `@latest` to go-get as long as there is a stable `v2.X.Y`.

**Comment by tredoe** [comment]
I intend to use v2.0.1 as a stable release so I changed the file 'go.mod' like you said. Thanks!
